---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../components/app

namespace: "dokuwiki"
namePrefix: "dokuwiki-"
images:
  - name: "lscr.io/linuxserver/dokuwiki"
    newTag: "2024-02-06a-ls211"

configMapGenerator:
  - name: app-config
    envs:
      - "app-config.env"
