---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../components/app

commonLabels:
  app.kubernetes.io/name: tku

namespace: "tku"
namePrefix: "tku-"
images:
  - name: "lscr.io/linuxserver/dokuwiki"
    newTag: "2024-02-06a-ls211"

configMapGenerator:
  - name: app-config
    envs:
      - "app-config.env"

patches:
  - target:
      kind: IngressRoute
      name: ingress
    patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`tku.hl.ancalagon.black`)
      - op: replace
        path: /spec/routes/0/services/0/name
        value: tku-svc
